CREATE TABLE COMMENTS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    THREADID INT FOREIGN KEY REFERENCES THREAD(ID),
    USERID INT FOREIGN KEY REFERENCES USER(ID),
    COMMENT VARCHAR(500)
)

CREATE TABLE THREAD(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
)


CREATE TABLE USER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25),
    PASSWORD VARCHAR(50)
)

